config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    # 「名前」は必須入力かつ20文字以内
    validates :name ,  presence: { message: "は必須入力"} , length: { maximum: 20 , message: "は20文字以内"}
    
    # 「内容」は必須入力かつ2文字以上30文字以下
    validates :body ,  presence: { message: "は必須入力"} , length: { maximum: 30, minimum: 2 , message: "は2文字以上30文字以下"} 

    # 「年齢」は必須入力かつ0以上。
    validates :age ,  presence: { message: "は必須入力"} , numericality: { only_integer: true, greater_than_or_equal_to: 0  , message: "は0以上"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

before_action :set_message , only: [:edit, :update, :destroy]

  def index
    @message = Message.new #create時に使う入れ物を用意している。
    # Messageを全て取得する。
    #複数形には意味があるのか？
    @messages = Message.all #viewで使うmessagesテーブルの内容を全て入れておく。
    # @messages = Message.find(4) #viewで使うmessagesテーブルの内容を全て入れておく。
    
  end
  
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージ保存しました。'
    else
      #メッセージのvalidationでエラーが出たとき
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end

  def edit
  end
  
  def show
      @message = Message.find(params[:id]) #URLから直接paramsを読んでいる。
      render 'show'
  end
  
  
  def update
    if @message.update(message_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end
  
  private
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end

  def set_message
    @message = Message.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>">Message Board</a>
      </div>
    </div>
  </nav>

  
  <div class="container">
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>
  
</body>
</html>

app/views/messages/_form.html.erb
    <div class="form-horizontal" role="form">
        <%= form_for(@message) do |f| %>
            <!-- ↓エラーが起きたときの表示 -->
            <% if @message.errors.present? %>
                <div class="alert alert-danger">
                    <%= alert %>
                    <ul>
                        <% @message.errors.full_messages.each do |full_message| %>
                            <li>
                                <%= full_message %>
                            </li>
                        <% end %> 
                    </ul>
                </div>
             <% end %>
            <!-- ↑エラーが起きたときの表示 -->

        
        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-sm-2 control-label">名前:</label>
            <div class="col-sm-10">
                <%= f.text_field :name, class: 'form-control', placeholder: '名前' %> 
            </div>
        </div>
        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-sm-2 control-label">年齢:</label>
            <div class="col-sm-10">
                <%= f.number_field :age, class: 'form-control', placeholder: '年齢' %>
            </div>
        </div>
        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-sm-2 control-label">内容:</label>
            <div class="col-sm-10">
                <%= f.text_area :body, class: 'form-control', placeholder: '内容', rows: '4' %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit "送信" , class: 'btn btn-primary btn-large btn-block' %>
            </div>
        </div>
        <% end %>
    </div>

app/views/messages/edit.html.erb
<h3>メッセージの編集</h3>

<%= render 'form' %>

app/views/messages/index.html.erb
<!-- 投稿の表示 -->
<div class="panel panel-default">
    <div class="panel-heading">
        メッセージ一覧
    </div>
    <div class="panel-body">
        <% @messages.each do |message| %>
    <div class = "row"> <!-- モバイルの時は1段組、それ以外は2段組 -->
        <div class = "col-xs-6 col-sm-2"><span class="label label-info"><%= message.name %></span></div>
        <div class = "col-xs-6 col-sm-2"><%= message.age %>才</span></div>
        <div class = "col-xs-12 col-sm-5"><%= simple_format(h(message.body)) %></div> <!-- 改行をきちんと表示する -->
        <div class = "col-xs-4 col-sm-3"><span class="label label-info"><%= link_to "表示" , message_path(message) %></span>/<span class="label label-info"><%= link_to "編集" , edit_message_path(message) %></span>/<span class="label label-info"><%= link_to "削除" , message , method: :delete, data: {confirm: '削除してもよろしいですか？'} %></span></div>
    </div>
        <% end %>
    </div>
</div>

<h3>投稿</h3>
<% #部分テンプレートを読み込んでいる %>
<%= render 'form'  %>

app/views/messages/show.html.erb
<h3><%= @message.name %>の投稿表示</h3>

    <div class="form-horizontal" role="form">
        <%= form_for(@message) do |f| %>
        
        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-sm-2 control-label">名前:</label>
            <div class="col-sm-10">
                <%= @message.name %>
            </div>
        </div>
        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-sm-2 control-label">年齢:</label>
            <div class="col-sm-10">
                <%= @message.age %>才
            </div>
        </div>
        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-sm-2 control-label">内容:</label>
            <div class="col-sm-10">
                <%= simple_format(h(@message.body)) %>
            </div>
        </div>
        <% end %>
    </div>